routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('uvas','Web\Uva\UvaController');
Route::resource('vinicolas', 'Web\Vinicola\VinicolaController');
Route::resource('enologos','Web\Enologo\EnologoController');
Route::resource('vinicolas','Web\Vinicola\VinicolaController');
Route::post('uvas/{uvaVin}/destroy','Web\Vinicola\UvaVinicolaController@destroy')->name('uvas.destroy');
Route::resource('bodegas','Web\Bodega\BodegaController');
Route::post('barrica/{barrica}/destroy','Web\Bodega\BodegaBarricaController@destroy')->name('barrica.destroy');
Route::resource('productores','Web\Productor\ProductorController');
Route::resource('barricas','Web\Barrica\BarricaController');
Route::resource('empleados','Web\Empleados\EmpleadosController');
Route::get('clientes', function(){
	return view('reporte.cliente');
})->name('clientes');
Route::get('ventas','VentasController@index')->name('ventas');
Route::get('puntos_corchos',function ()
{
	$users = App\User::get();
	return view('reporte.pcorcho',['users'=>$users]);
})->name('puntos_corchos');
Route::get('viajes', function (){
	return view('reporte.viajes');
})->name('viajes');
Route::get('cursos', function (){
	return view('reporte.cursos');
})->name('cursos');
Route::get('prodBodega/{id}','Web\Productor\ProductorController@bodega');
Route::get('prodVinicola/{id}','Web\Productor\ProductorController@vinicola');
Route::get('prodBarricas/{id}','Web\Productor\ProductorController@barricas');
Route::get('prodUvas/{id}','Web\Productor\ProductorController@uvas');
Route::get('bodBarricas/{id}','Web\Bodega\BodegaController@barricas');
Route::get('bodUvas/{id}','Web\Bodega\BodegaController@uvas');

Route::get('getEnologos','Web\Enologo\EnologoController@enologos');

Route::get('getWineMaker','Web\Enologo\EnologoController@wine');

app/Uva.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Uva extends Model
{
    //
    
    protected $table = "uvas";

    protected $fillable=[
    	'title',
    	'subtitle',
    	'image',
    	'olfato',
    	'gusto',
    	'vista',
    	'maridaje',
    ];

   	protected $hidden=[
   		'created_at',
   		'updated_at'
   	];

   	public function uvasVinicolas(){
   		return $this->hasMany('App\UvaVinicola', 'uva_id','id');
   	}
}

app/Http/Controllers/Api/Uva/UvaController.php
<?php

namespace App\Http\Controllers\Api\Uva;

use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UvaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $uvas = Uva::orderBy('title','asc')->get();
        
        return response()->json(['uvas'=>$uvas],202);
        

    }

   
    /**
     * Display the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function show(Uva $uva)
    {
        //
    }


}

app/Http/Controllers/Web/Uva/UvaController.php
<?php

namespace App\Http\Controllers\Web\Uva;

use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;


class UvaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $uvas = Uva::orderBy('title','asc')->paginate(5);
        return view('uvas.index',['uvas'=>$uvas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        return view('uvas.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->image['-originalName']);
        $rules = [
            'title'=>'required|unique:uvas',
            'image'=>'required',
        ];
        $this->validate($request, $rules);
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            //
            // dd("valido");

            $path = $request->image->storeAs('images', $request->title.".jpg", 'public');
            $uva = Uva::create([
                'title'=> $request->title,
                'subtitle'=>$request->subtitle,
                'image' => "storage/$path",
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd($path);
        }
        else{
            dd("invalid");
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function show(Uva $uva)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function edit(Uva $uva)
    {
        //
        $edit = true;
        return view('uvas.form',['edit'=>$edit,'uva'=>$uva]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Uva $uva)
    {
        //
        // $rules = [
        //     // 'title'=>'required|unique:uvas',
        //     'image'=>'required',
        // ];
        // $this->validate($request, $rules);
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            //
            // dd("valido");

            $path = $request->image->storeAs('images', $uva->title.".jpg", 'public');
            // Storage::delete($uva->image);
            $uva->update([
                'subtitle'=>$request->subtitle,
                'image' => "storage/$path",
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd($path);
        }
        else{
            $uva->update([
                'subtitle'=>$request->subtitle,
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd("invalid");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function destroy(Uva $uva)
    {
        //
        // dd($uva);
        $uva->delete();
        return redirect()->route('uvas.index');
    }
}

resources/views/uvas/form.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						{{$edit ? $uva->title : "Nueva uva"}}
					</div>
					<div class="card-body">
						<form method="POST" enctype="multipart/form-data" action="{{ $edit ? route('uvas.update',['uva'=>$uva]) : route('uvas.store') }}">
							@csrf
							{{-- {{dd($uva)}} --}}
							@if ($edit)
								<input type="hidden" name="_method" value="PUT">
							@endif
							<div class="form-group row">
								<label for="title" class="col-md-4 col-form-label text-md-right">Nombre de la uva:</label>
								<div class="col-md-6">
									<input class="form-control {{ $errors->has('title') ? ' is-invalid' : ''  }}" id="title" {{$edit ? 'disabled' : ""}} type="text" name="title" value="{{ $edit ? $uva->title : old('title') }}" required>
									@if ($errors->has('title'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("title")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="subtitle" class="col-md-4 col-form-label text-md-right">Otros nombres (si tiene):</label>
								<div class="col-md-6">
									<input class="form-control {{ $errors->has('subtitle') ? ' is-invalid' : ''  }}" id="subtitle" type="text" name="subtitle" value="{{ $edit ? $uva->subtitle : old('subtitle') }}">
									@if ($errors->has('subtitle'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("subtitle")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="olfato" class="col-md-4 col-form-label text-md-right">¿Cómo es al olfato?:</label>
								<div class="col-md-6">
									<textarea class="form-control {{ $errors->has('olfato') ? ' is-invalid' : ''  }}" id="olfato" name="olfato">{{$edit ? $uva->olfato : old('olfato')}}</textarea>
									@if ($errors->has('olfato'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("olfato")}}</strong>
										</span>
									@endif
								</div>
							</div>

							<div class="form-group row">
								<label for="gusto" class="col-md-4 col-form-label text-md-right">¿Cómo es al gusto?:</label>
								<div class="col-md-6">
									<textarea class="form-control {{ $errors->has('gusto') ? ' is-invalid' : ''  }}" id="gusto" name="gusto">{{$edit ? $uva->gusto : old('gusto')}}</textarea>
									@if ($errors->has('gusto'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("gusto")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="vista" class="col-md-4 col-form-label text-md-right">¿Cómo es a la vista?:</label>
								<div class="col-md-6">
									<textarea class="form-control {{ $errors->has('vista') ? ' is-invalid' : ''  }}" id="vista" name="vista">{{$edit ? $uva->vista : old('vista')}}</textarea>
									@if ($errors->has('vista'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("vista")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="maridaje" class="col-md-4 col-form-label text-md-right">Maridaje perfecto:</label>
								<div class="col-md-6">
									<textarea class="form-control {{ $errors->has('maridaje') ? ' is-invalid' : ''  }}" id="maridaje" name="maridaje">{{$edit ? $uva->maridaje : old('maridaje')}}</textarea>
									@if ($errors->has('maridaje'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("maridaje")}}</strong>
										</span>
									@endif
								</div>
							</div>
							@if ($edit)
								{{-- expr --}}
							<div class="form-group row">
								<div class="container">
									<img src="{{ url($uva->image) }}" >
								</div>
							</div>
							@endif
							<div class="form-group row">
								<label for="image" class="col-md-4 col-form-label text-md-right">Imagen de la uva:</label>
								<input type="file" id="image" name="image" class="file">
							</div>
							<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/uvas/index.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container-fluid">
		<div class="col-6 input-group input-group-lg mb-3">
		  <div class="input-group-prepend">
		    <span class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></span>
		  </div>
		  <input type="text" class="form-control" placeholder="Buscar.." aria-label="Buscar.." aria-describedby="basic-addon1">
		</div>
		<div class="col-3 input-group input-group-lg mb-3">
		  <a href="{{ route('uvas.create') }}" class="btn btn-primary">Agregar Nueva Uva</a>
		</div>
		<br>
		<br>
		<div class="container-fluid">
			<table class="table">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Nombre de la uva</th>
						<th scope="col">Otros nombres</th>
						<th scope="col">Al olfato</th>
						<th scope="col">Al gusto</th>
						<th scope="col">A la vista</th>
						<th scope="col">Maridajes</th>
						<th scope="col">Acciones</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($uvas as $uva)
						{{-- expr --}}
					<tr>
						<th scope="row">{{$uva->title}}</th>
						<th>{{$uva->subtitle}}</th>
						<th>{{$uva->olfato}}</th>
						<th>{{$uva->gusto}}</th>
						<th>{{$uva->vista}}</th>
						<th>{{$uva->maridaje}}</th>
						<th>
							<a href="{{ route('uvas.edit',['uva'=>$uva]) }}" class="btn btn-primary">Editar</a>
							<form method="POST" action="{{ route('uvas.destroy',['uva'=>$uva]) }}">
								@csrf
								<input type="hidden" name="_method" value="DELETE">
								<button action="submit" onclick="return confirm('¿Estás seguro que desea eliminar esta uva?');" class="btn btn-danger">Borrar</button>
								
							</form>
						</th>
					</tr>
					@empty
						{{-- empty expr --}}
						No hay uvas 
					@endforelse
					
				</tbody>
			</table>
			{{ $uvas->links() }}
		</div>
	</div>
@endsection