routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('uvas','Web\Uva\UvaController');
Route::resource('vinicolas', 'Web\Vinicola\VinicolaController');
Route::resource('enologos','Web\Enologo\EnologoController');
Route::resource('vinicolas','Web\Vinicola\VinicolaController');
Route::post('uvas/{uvaVin}/destroy','Web\Vinicola\UvaVinicolaController@destroy')->name('uvas.destroy');
Route::resource('bodegas','Web\Bodega\BodegaController');
Route::post('barrica/{barrica}/destroy','Web\Bodega\BodegaBarricaController@destroy')->name('barrica.destroy');
Route::resource('productores','Web\Productor\ProductorController');
Route::resource('barricas','Web\Barrica\BarricaController');
Route::resource('empleados','Web\Empleados\EmpleadosController');
Route::get('clientes', function(){
	return view('reporte.cliente');
})->name('clientes');
Route::get('ventas','VentasController@index')->name('ventas');
Route::get('puntos_corchos',function ()
{
	$users = App\User::get();
	return view('reporte.pcorcho',['users'=>$users]);
})->name('puntos_corchos');
Route::get('viajes', function (){
	return view('reporte.viajes');
})->name('viajes');
Route::get('cursos', function (){
	return view('reporte.cursos');
})->name('cursos');
Route::get('prodBodega/{id}','Web\Productor\ProductorController@bodega');
Route::get('prodVinicola/{id}','Web\Productor\ProductorController@vinicola');
Route::get('prodBarricas/{id}','Web\Productor\ProductorController@barricas');
Route::get('prodUvas/{id}','Web\Productor\ProductorController@uvas');
Route::get('bodBarricas/{id}','Web\Bodega\BodegaController@barricas');
Route::get('bodUvas/{id}','Web\Bodega\BodegaController@uvas');

Route::get('getEnologos','Web\Enologo\EnologoController@enologos');

Route::get('getWineMaker','Web\Enologo\EnologoController@wine');

app/Uva.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Uva extends Model
{
    //
    
    protected $table = "uvas";

    protected $fillable=[
    	'title',
    	'subtitle',
    	'image',
    	'olfato',
    	'gusto',
    	'vista',
    	'maridaje',
    ];

   	protected $hidden=[
   		'created_at',
   		'updated_at'
   	];

   	public function uvasVinicolas(){
   		return $this->hasMany('App\UvaVinicola', 'uva_id','id');
   	}
}

app/Vinicola.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vinicola extends Model
{
    //
    protected $table="vinicola";

    protected $fillable=[
    	'id',
    	'tipo',
    	'nombre',
    	'distinciones',
    	'inicio',
    	'filosofia',
    	'locacion',
    	'lat',
    	'long',
    	'contacto',
    	'puesto',
    	'correo',
    	'celular',
    	'telefono',
    	'comentarios',
    	'hectareas'
    ];
    
    protected $hidden=[
    	'created_at',
    	'updated_at'
    ];
    public function productores()
    {
    	return $this->hasMany('App\Productor','vinicola_id','id');
    }
    public function uvasVin()
    {
        return $this->morphMany('App\UvaProducida', 'producidas');
    }
    public function getMapLink(){
        return 'https://www.google.com.mx/maps?q=' . $this->lat . ',' . $this->long;
    }
}

app/Http/Controllers/Api/Uva/UvaController.php
<?php

namespace App\Http\Controllers\Api\Uva;

use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UvaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $uvas = Uva::orderBy('title','asc')->get();
        
        return response()->json(['uvas'=>$uvas],202);
        

    }

   
    /**
     * Display the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function show(Uva $uva)
    {
        //
    }


}

app/Http/Controllers/Api/Vinicola/VinicolaController.php
<?php

namespace App\Http\Controllers\Api\Vinicola;

use App\Vinicola;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VinicolaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $vinicolas = Vinicola::get();
        if ($vinicolas->count() == 0) {
            # code...
            return response()->json(['message'=>"No hay registro"],404);
        } else {
            # code...
            return response()->json(['vinicolas'=>$vinicolas],202);
        }
        

    }

    
    /**
     * Display the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function show(Vinicola $vinicola)
    {
        //
    }

}

app/Http/Controllers/Web/Uva/UvaController.php
<?php

namespace App\Http\Controllers\Web\Uva;

use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;


class UvaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $uvas = Uva::orderBy('title','asc')->paginate(5);
        return view('uvas.index',['uvas'=>$uvas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        return view('uvas.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->image['-originalName']);
        $rules = [
            'title'=>'required|unique:uvas',
            'image'=>'required',
        ];
        $this->validate($request, $rules);
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            //
            // dd("valido");

            $path = $request->image->storeAs('images', $request->title.".jpg", 'public');
            $uva = Uva::create([
                'title'=> $request->title,
                'subtitle'=>$request->subtitle,
                'image' => "storage/$path",
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd($path);
        }
        else{
            dd("invalid");
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function show(Uva $uva)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function edit(Uva $uva)
    {
        //
        $edit = true;
        return view('uvas.form',['edit'=>$edit,'uva'=>$uva]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Uva $uva)
    {
        //
        // $rules = [
        //     // 'title'=>'required|unique:uvas',
        //     'image'=>'required',
        // ];
        // $this->validate($request, $rules);
        if ($request->hasFile('image') && $request->file('image')->isValid()) {
            //
            // dd("valido");

            $path = $request->image->storeAs('images', $uva->title.".jpg", 'public');
            // Storage::delete($uva->image);
            $uva->update([
                'subtitle'=>$request->subtitle,
                'image' => "storage/$path",
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd($path);
        }
        else{
            $uva->update([
                'subtitle'=>$request->subtitle,
                'olfato' => $request->olfato,
                'gusto'=>$request->gusto,
                'vista'=>$request->vista,
                'maridaje'=>$request->maridaje
            ]);
            return redirect()->route('uvas.index');
            // dd("invalid");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Uva  $uva
     * @return \Illuminate\Http\Response
     */
    public function destroy(Uva $uva)
    {
        //
        // dd($uva);
        $uva->delete();
        return redirect()->route('uvas.index');
    }
}

app/Http/Controllers/Web/Vinicola/UvaVinicolaController.php
<?php

namespace App\Http\Controllers\Web\Vinicola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\UvaProducida;

class UvaVinicolaController extends Controller
{
    //
    public function destroy(UvaProducida $uvaVin)
    {
    	$uvaVin->delete();
    	return redirect()->route('vinicolas.index');
    }
}

app/Http/Controllers/Web/Vinicola/VinicolaController.php
<?php

namespace App\Http\Controllers\Web\Vinicola;

use App\Vinicola;
use App\UvaProducida;
use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class VinicolaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $vinicolas = Vinicola::orderBy('nombre','asc')->paginate(5);
        return view('vinicola.index',['vinicolas'=>$vinicolas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        $uvas= Uva::orderBy('title','asc')->get();
        return view('vinicola.form',['edit'=>$edit,'uvas'=>$uvas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd(sizeof($request->input('uva')));
        $rules = [
            'nombre'=> 'required|unique:vinicola',
            'tipo' => 'required',
            'inicio'=> 'required',
            'filosofia'=> 'required',
            'locacion'=> 'required',
            'uva' =>'required',
            'telefono'=> 'required'
        ];
        $validater = $this->validate($request,$rules);
        $vinicola = Vinicola::create($request->all());
        for ($i = 0; $i < sizeof($request->input('uva')) ; $i++) {
            UvaProducida::create([
                'producidas_id'=>$vinicola->id,
                'producidas_type'=>"App\Vinicola",
                'uva_id'=>$request->uva[$i],
                'hectarea'=>$request->hectarea[$i]
            ]);
            
        }
        return redirect()->route('vinicolas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function show(Vinicola $vinicola)
    {
        //
        // dd($vinicola);
        return view('vinicola.show',['vinicola'=>$vinicola]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function edit(Vinicola $vinicola)
    {
        //
        $edit = true;
        $uvas= Uva::orderBy('title','asc')->get();
        return view('vinicola.form',['vinicola'=>$vinicola,'edit'=>$edit,'uvas'=>$uvas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vinicola $vinicola)
    {
        //
        // dd($request->all());
        // dd($vinicola);
         $rules = [
            // 'nombre'=> 'required|unique:vinicola',
            'tipo' => 'required',
            'inicio'=> 'required',
            'filosofia'=> 'required',
            'locacion'=> 'required',

            'telefono'=> 'required'
        ];
        $validater = $this->validate($request,$rules);
        $vinicola->update([
            'tipo'=>$request->tipo,
            'distinciones'=>$request->distinciones,
            'inicio'=>$request->inicio,
            'filosofia'=>$request->filosofia,
            'locacion'=>$request->locacion,
            'lat'=>$request->lat,
            'long'=>$request->long,
            'contacto'=>$request->contacto,
            'puesto'=>$request->puesto,
            'correo'=>$request->correo,
            'celular'=>$request->celular,
            'telefono'=>$request->telefono,
            'comentarios'=>$request->comentarios,
            'hectareas'=>$request->hectareas
        ]);
        if ($request->uva[0] != null) {
            for ($i = 0; $i < sizeof($request->input('uva')) ; $i++) {
                UvaProducida::create([
                    'producidas_id'=>$vinicola->id,
                    'producidas_type'=>"App\Vinicola",
                    'uva_id'=>$request->uva[$i],
                    'hectarea'=>$request->hectarea[$i]
                ]);
                
            }
        }
        
        // $vinicola->save();
        return redirect()->route('vinicolas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vinicola $vinicola)
    {
        //
        foreach ($vinicola->uvasVin as $uvaVin) {
            $uvaVin->delete();
        }
        $vinicola->delete();
        return redirect()->route('vinicolas.index');
    }
}

resources/views/vinicola/uvas/form.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Vinicola/Bodega
					</div>
					<ul class="nav nav-tabs">
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.show',$vinicola) }}">{{$vinicola->nombre}}</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.marcas.index',$vinicola) }}">Marcas de la bodega</a>
						</li>
						<li class="nav-item">
							<a class="nav-link active" href="{{ route('vinicolas.uvas.index',$vinicola) }}" >Tipo de uvas</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.barricas.index',$vinicola) }}" >Barricas</a>
						</li>
					</ul>
					<div class="card-body">
						<form method="POST" action="{{ $edit ? route('vinicolas.uvas.update',[$vinicola,$uva]) : route('vinicolas.uvas.store',$vinicola) }}">
							@csrf

							@if ($edit)
								{{-- expr --}}
								<input type="hidden" name="_method" value="PUT">
							@endif
							<input type="hidden" name="vinicola_id" value="{{$vinicola->id}}">
							<div class="form-group row">
								<label for="uva_id" class="col-md-4 col-form-label text-md-right">Tipo de uva:</label>
								<div class="col-md-6">
									<select name="uva_id" class="form-control {{ $errors->has('uva_id') ? 'is-invalid' : '' }}" value="{{$edit ? $uva->uva_id : old('uva_id')}}">
										<option value="">Seleccione la uva</option>
										@foreach ($uvas as $uva)
											{{-- expr --}}
											<option value="{{$uva->id}}">{{$uva->title}}</option>
										@endforeach
									</select>
									@if ($errors->has('uva_id'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("uva_id")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">		
								<label for="hectareas" class="col-md-4 col-form-label text-md-right">Hectareas cosechadas:</label>
								<div class="input-group col-md-6">
									<input type="number" class="form-control {{ $errors->has('hectareas') ? 'is-invalid' : '' }}" name="hectareas" min="0" step="0.01" value="{{$edit ? $uva->hectareas : old('hectareas')}}">
									<div class="input-group-append">
    									<span class="input-group-text"><strong>ha</strong></span>
									</div>
									@if ($errors->has('hectareas'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("hectareas")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row mb-0">
	                            <div class="col-md-6 offset-md-4">
	                                <button type="submit" class="btn btn-primary">
	                                    Guardar cosecha
	                                </button>
	                            </div>
	                        </div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/vinicola/uvas/index.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Vinicola/Bodega
					</div>
					<ul class="nav nav-tabs">
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.show',$vinicola) }}">{{$vinicola->nombre}}</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.marcas.index',$vinicola) }}">Marcas de la bodega</a>
						</li>
						<li class="nav-item">
							<a class="nav-link active" href="{{ route('vinicolas.uvas.index',$vinicola) }}" >Tipo de uvas</a>
						</li>
						<li class="nav-item">
								<a class="nav-link" href="{{ route('vinicolas.barricas.index',$vinicola) }}" >Barricas</a>
							</li>
					</ul>
					<div class="card-body">
						<div class="container-fluid">
							<div class="col-6 input-group input-group-lg mb-3">
								<a href="{{ route('vinicolas.uvas.create',['vinicola'=>$vinicola]) }}" class="btn btn-primary">Nueva Uva/Cosecha</a>
							</div>
							<br>
							<br>
							<table class="table">
									<thead class="thead-dark">
										<tr>
											<th scope="col">Uva</th>
											<th scope="col">Hectareas sembradas</th>
										</tr>
									</thead>
									<tbody>
										@forelse ($uvas as $uva)
											{{-- expr --}}
											<tr>
												<th scope="row">{{$uva->nombre}}</th>
												<th>{{$uva->hectareas}}  <strong>ha</strong></th>
											</tr>
										@empty
											{{-- empty expr --}}
											<span>No hay Uvas</span>
										@endforelse
											
									</tbody>
								</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection