routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('uvas','Web\Uva\UvaController');
Route::resource('vinicolas', 'Web\Vinicola\VinicolaController');
Route::resource('enologos','Web\Enologo\EnologoController');
Route::resource('vinicolas','Web\Vinicola\VinicolaController');
Route::post('uvas/{uvaVin}/destroy','Web\Vinicola\UvaVinicolaController@destroy')->name('uvas.destroy');
Route::resource('bodegas','Web\Bodega\BodegaController');
Route::post('barrica/{barrica}/destroy','Web\Bodega\BodegaBarricaController@destroy')->name('barrica.destroy');
Route::resource('productores','Web\Productor\ProductorController');
Route::resource('barricas','Web\Barrica\BarricaController');
Route::resource('empleados','Web\Empleados\EmpleadosController');
Route::get('clientes', function(){
	return view('reporte.cliente');
})->name('clientes');
Route::get('ventas','VentasController@index')->name('ventas');
Route::get('puntos_corchos',function ()
{
	$users = App\User::get();
	return view('reporte.pcorcho',['users'=>$users]);
})->name('puntos_corchos');
Route::get('viajes', function (){
	return view('reporte.viajes');
})->name('viajes');
Route::get('cursos', function (){
	return view('reporte.cursos');
})->name('cursos');
Route::get('prodBodega/{id}','Web\Productor\ProductorController@bodega');
Route::get('prodVinicola/{id}','Web\Productor\ProductorController@vinicola');
Route::get('prodBarricas/{id}','Web\Productor\ProductorController@barricas');
Route::get('prodUvas/{id}','Web\Productor\ProductorController@uvas');
Route::get('bodBarricas/{id}','Web\Bodega\BodegaController@barricas');
Route::get('bodUvas/{id}','Web\Bodega\BodegaController@uvas');

Route::get('getEnologos','Web\Enologo\EnologoController@enologos');

Route::get('getWineMaker','Web\Enologo\EnologoController@wine');

app/Vinicola.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vinicola extends Model
{
    //
    protected $table="vinicola";

    protected $fillable=[
    	'id',
    	'tipo',
    	'nombre',
    	'distinciones',
    	'inicio',
    	'filosofia',
    	'locacion',
    	'lat',
    	'long',
    	'contacto',
    	'puesto',
    	'correo',
    	'celular',
    	'telefono',
    	'comentarios',
    	'hectareas'
    ];
    
    protected $hidden=[
    	'created_at',
    	'updated_at'
    ];
    public function productores()
    {
    	return $this->hasMany('App\Productor','vinicola_id','id');
    }
    public function uvasVin()
    {
        return $this->morphMany('App\UvaProducida', 'producidas');
    }
    public function getMapLink(){
        return 'https://www.google.com.mx/maps?q=' . $this->lat . ',' . $this->long;
    }
}

app/Http/Controllers/Api/Vinicola/VinicolaController.php
<?php

namespace App\Http\Controllers\Api\Vinicola;

use App\Vinicola;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VinicolaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $vinicolas = Vinicola::get();
        if ($vinicolas->count() == 0) {
            # code...
            return response()->json(['message'=>"No hay registro"],404);
        } else {
            # code...
            return response()->json(['vinicolas'=>$vinicolas],202);
        }
        

    }

    
    /**
     * Display the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function show(Vinicola $vinicola)
    {
        //
    }

}

app/Http/Controllers/Web/Vinicola/UvaVinicolaController.php
<?php

namespace App\Http\Controllers\Web\Vinicola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\UvaProducida;

class UvaVinicolaController extends Controller
{
    //
    public function destroy(UvaProducida $uvaVin)
    {
    	$uvaVin->delete();
    	return redirect()->route('vinicolas.index');
    }
}

app/Http/Controllers/Web/Vinicola/VinicolaController.php
<?php

namespace App\Http\Controllers\Web\Vinicola;

use App\Vinicola;
use App\UvaProducida;
use App\Uva;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class VinicolaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $vinicolas = Vinicola::orderBy('nombre','asc')->paginate(5);
        return view('vinicola.index',['vinicolas'=>$vinicolas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        $uvas= Uva::orderBy('title','asc')->get();
        return view('vinicola.form',['edit'=>$edit,'uvas'=>$uvas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd(sizeof($request->input('uva')));
        $rules = [
            'nombre'=> 'required|unique:vinicola',
            'tipo' => 'required',
            'inicio'=> 'required',
            'filosofia'=> 'required',
            'locacion'=> 'required',
            'uva' =>'required',
            'telefono'=> 'required'
        ];
        $validater = $this->validate($request,$rules);
        $vinicola = Vinicola::create($request->all());
        for ($i = 0; $i < sizeof($request->input('uva')) ; $i++) {
            UvaProducida::create([
                'producidas_id'=>$vinicola->id,
                'producidas_type'=>"App\Vinicola",
                'uva_id'=>$request->uva[$i],
                'hectarea'=>$request->hectarea[$i]
            ]);
            
        }
        return redirect()->route('vinicolas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function show(Vinicola $vinicola)
    {
        //
        // dd($vinicola);
        return view('vinicola.show',['vinicola'=>$vinicola]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function edit(Vinicola $vinicola)
    {
        //
        $edit = true;
        $uvas= Uva::orderBy('title','asc')->get();
        return view('vinicola.form',['vinicola'=>$vinicola,'edit'=>$edit,'uvas'=>$uvas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vinicola $vinicola)
    {
        //
        // dd($request->all());
        // dd($vinicola);
         $rules = [
            // 'nombre'=> 'required|unique:vinicola',
            'tipo' => 'required',
            'inicio'=> 'required',
            'filosofia'=> 'required',
            'locacion'=> 'required',

            'telefono'=> 'required'
        ];
        $validater = $this->validate($request,$rules);
        $vinicola->update([
            'tipo'=>$request->tipo,
            'distinciones'=>$request->distinciones,
            'inicio'=>$request->inicio,
            'filosofia'=>$request->filosofia,
            'locacion'=>$request->locacion,
            'lat'=>$request->lat,
            'long'=>$request->long,
            'contacto'=>$request->contacto,
            'puesto'=>$request->puesto,
            'correo'=>$request->correo,
            'celular'=>$request->celular,
            'telefono'=>$request->telefono,
            'comentarios'=>$request->comentarios,
            'hectareas'=>$request->hectareas
        ]);
        if ($request->uva[0] != null) {
            for ($i = 0; $i < sizeof($request->input('uva')) ; $i++) {
                UvaProducida::create([
                    'producidas_id'=>$vinicola->id,
                    'producidas_type'=>"App\Vinicola",
                    'uva_id'=>$request->uva[$i],
                    'hectarea'=>$request->hectarea[$i]
                ]);
                
            }
        }
        
        // $vinicola->save();
        return redirect()->route('vinicolas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vinicola  $vinicola
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vinicola $vinicola)
    {
        //
        foreach ($vinicola->uvasVin as $uvaVin) {
            $uvaVin->delete();
        }
        $vinicola->delete();
        return redirect()->route('vinicolas.index');
    }
}

resources/views/vinicola/index.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container-fluid">
		<div class="container">
			<div class="col">
				<h1>Vinicolas/Ranchos</h1>
			</div>
			<div class="col-3 input-group input-group-lg mb-3">
		  		<a href="{{ route('vinicolas.create') }}" class="btn btn-primary">Agregar Nuevo Vinicola/Rancho</a>
			</div>
		</div>
		<br>
		<br>
		<br>
		<br>
		<div class="container-fluid">
			<table class="table">
				<thead class="thead-dark">
					<tr>
						<th scope="col" style="width: 190px">Nombre</th>
						<th scope="col">tipo</th>
						<th scope="col" style="width: 500px;">Filosofía</th>
						<th scope="col">Locación</th>
						<th scope="col">Uvas</th>
						<th scope="col">Telefono</th>
						<th scope="col">Accion</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($vinicolas as $vinicola)
						{{-- expr --}}
						<tr>
							<th scope="row">{{$vinicola->nombre}}</th>
							<th>{{$vinicola->tipo}}</th>
							<th>{{$vinicola->filosofia}}</th>
							<th>{{$vinicola->locacion}}
								<br>
								<a href="{{$vinicola->getMapLink()}}" target="_blank">Ver en Google Maps</a>
							</th>
							<th>
								@forelse ($vinicola->uvasVin as $uvaVin)
									{{-- expr --}}
									{{$uvaVin->uva['title']}} {{$uvaVin->hectarea}} ha
									<form action="{{ route('uvas.destroy',['uvaVin'=>$uvaVin]) }}" method="POST">
									@csrf
									<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar esta uva?');">Eliminar</button>
								</form>
								
								@empty
									{{-- empty expr --}}
									No tienes uvas
								@endforelse
							</th>
							<th>{{$vinicola->telefono}}</th>
							<th>
								<a class="btn btn-default" href="{{ route('vinicolas.edit',[$vinicola]) }}">Editar</a>
								<form action="{{ route('vinicolas.destroy',[$vinicola]) }}" method="POST">
									<input type="hidden" name="_method" value="DELETE">
									@csrf
									<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar este {{$vinicola->tipo}}?');">Eliminar</button>
								</form>
							</th>
						</tr>
					@empty
						<div class="alert alert-danger" role="alert">
							<span>No hay vinicolas/ranchos</span>
						</div>
					@endforelse
				</tbody>
			</table>
		</div>
	</div>
@endsection

resources/views/vinicola/show.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8">
					<div class="card">
						<div class="card-header">
						Vinicola/Bodega
					</div>
					<ul class="nav nav-tabs">
						<li class="nav-item">
							<a class="nav-link active" href="{{ route('vinicolas.show',$vinicola) }}">{{$vinicola->nombre}}</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.marcas.index',$vinicola) }}">Marcas de la bodega</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.uvas.index',$vinicola) }}" >Tipo de uvas</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{{ route('vinicolas.barricas.index',$vinicola) }}" >Barricas</a>
						</li>
					</ul>
					<div class="card-body">
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Nombre de la bodega:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->nombre }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Distinciones:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->distinciones ? $vinicola->distinciones : "Sin distinciones por el momento" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Año de inicio:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->inicio }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Filosofía:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->filosofia }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Locación de la bodega:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->locacion }}</p>
								<br>
								<a href="{{$vinicola->getMapLink() ? $vinicola->getMapLink() : "#"}}" target="_blank">Ver en mapa</a>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Enologo:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->enologo }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Wine Maker:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->wine_maker ? $vinicola->wine_maker : "Esta bodega no tiene Wine Maker." }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label class="col-md-4 col-form-label text-md-right">Nombre completo del contacto:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->contacto ? $vinicola->contacto : "Información no proporcionada" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label for="puesto" class="col-md-4 col-form-label text-md-right">Puesto del contacto:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->puesto ? $vinicola->puesto : "Información no proporcionada" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label for="correo" class="col-md-4 col-form-label text-md-right">Correo electronico del contacto:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->correo ? $vinicola->correo : "Información no proporcionada" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label for="celular" class="col-md-4 col-form-label text-md-right">Telefono celular del contacto:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->celular ? $vinicola->celular : "Información no proporcionada" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label for="telefono" class="col-md-4 col-form-label text-md-right">Telefono de la bodega:</label>
							<div class="col-md-6">
								<p>{{ $vinicola->telefono }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<label for="observacion" class="col-md-4 col-form-label text-md-right">Observación de la bodega:</label>
							<div class="col-md-6">
								<p >{{ $vinicola->fecha_observacion ? $vinicola->fecha_observacion : "" }}{{ $vinicola->observaciones ? $vinicola->observaciones : "" }}</p>
							</div>
						</div>
						<div class="col-md-12">
							<div class="col-md-4">
								<a href="{{ route('vinicolas.edit',["vinicola"=>$vinicola]) }}" class="btn btn-primary">Editar {{$vinicola->nombre}}</a>
							</div>
							<div class="offset-md-2 col-md-4">
								<a href="{{ route('vinicolas.create') }}" class="btn btn-primary">Nueva Bodega</a>
							</div>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection