routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('uvas','Web\Uva\UvaController');
Route::resource('vinicolas', 'Web\Vinicola\VinicolaController');
Route::resource('enologos','Web\Enologo\EnologoController');
Route::resource('vinicolas','Web\Vinicola\VinicolaController');
Route::post('uvas/{uvaVin}/destroy','Web\Vinicola\UvaVinicolaController@destroy')->name('uvas.destroy');
Route::resource('bodegas','Web\Bodega\BodegaController');
Route::post('barrica/{barrica}/destroy','Web\Bodega\BodegaBarricaController@destroy')->name('barrica.destroy');
Route::resource('productores','Web\Productor\ProductorController');
Route::resource('barricas','Web\Barrica\BarricaController');
Route::resource('empleados','Web\Empleados\EmpleadosController');
Route::get('clientes', function(){
	return view('reporte.cliente');
})->name('clientes');
Route::get('ventas','VentasController@index')->name('ventas');
Route::get('puntos_corchos',function ()
{
	$users = App\User::get();
	return view('reporte.pcorcho',['users'=>$users]);
})->name('puntos_corchos');
Route::get('viajes', function (){
	return view('reporte.viajes');
})->name('viajes');
Route::get('cursos', function (){
	return view('reporte.cursos');
})->name('cursos');
Route::get('prodBodega/{id}','Web\Productor\ProductorController@bodega');
Route::get('prodVinicola/{id}','Web\Productor\ProductorController@vinicola');
Route::get('prodBarricas/{id}','Web\Productor\ProductorController@barricas');
Route::get('prodUvas/{id}','Web\Productor\ProductorController@uvas');
Route::get('bodBarricas/{id}','Web\Bodega\BodegaController@barricas');
Route::get('bodUvas/{id}','Web\Bodega\BodegaController@uvas');

Route::get('getEnologos','Web\Enologo\EnologoController@enologos');

Route::get('getWineMaker','Web\Enologo\EnologoController@wine');

app/Enologo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Enologo extends Model
{
    //

    protected $table="enologo";

    protected $fillable=[
    	'id',
    	'nombre',
    	'paterno',
    	'materno',
    	'tipo',
    	'cv'
    ];

    protected $hidden=[
    	'created_at',
    	'updated_at'
    ];

    
}

app/Http/Controllers/Web/Enologo/EnologoController.php
<?php

namespace App\Http\Controllers\Web\Enologo;

use App\Enologo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EnologoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $enologos= Enologo::paginate(15);
        return view('enologo.index',['enologos'=>$enologos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit= false;
        return view('enologo.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = [
            'nombre'=>'required',
            'paterno'=>"required",
            'tipo'=>'required',
            'cv'=>"required"
        ];
        $this->validate($request,$rules);
        $enologo=Enologo::create($request->all());
        return redirect()->route('enologos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Enologo  $enologo
     * @return \Illuminate\Http\Response
     */
    public function show(Enologo $enologo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Enologo  $enologo
     * @return \Illuminate\Http\Response
     */
    public function edit(Enologo $enologo)
    {
        //
        // dd($enologo);
         $edit= true;
        return view('enologo.form',['edit'=>$edit,'enologo'=>$enologo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Enologo  $enologo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Enologo $enologo)
    {
        //
        $rules = [
            'nombre'=>'required',
            'paterno'=>"required",
            'tipo'=>'required',
            'cv'=>"required"
        ];
        $this->validate($request,$rules);
        $enologo->update($request->all());
        return redirect()->route('enologos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Enologo  $enologo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Enologo $enologo)
    {
        //
        $enologo->delete();
        return redirect()->route('enologos.index');

    }

    public function enologos()
    {
        $enologos = Enologo::where('tipo','Enólogo')->get();
        return response()->json(['enologos'=>$enologos],201);
    }

    public function wine()
    {
        $wine_makers = Enologo::where('tipo','Wine Maker')->get();
        return response()->json(['wine_makers'=>$wine_makers],201);
    }
}

resources/views/enologo/form.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Enólogo/Wine Maker
					</div>
					
					<div class="card-body">
						<form method="POST" action="{{ $edit == false ? route('enologos.store') : route('enologos.update',['enologo'=>$enologo]) }}">
							@csrf

							@if ($edit == true)
								{{-- expr --}}
								<input type="hidden" name="_method" value="PUT">
							@endif

							<div class="form-group row">
								<label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre del enólogo:</label>
								<div class="col-md-6">
									<input id="nombre" type="text" class="form-control {{ $errors->has('nombre') ? ' is-invalid' : ''  }}" name="nombre" value="{{ $edit ? $enologo->nombre : old('nombre') }}" required autofocus="">
									@if ($errors->has('nombre'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("nombre")}}</strong>
										</span>
									@endif
								</div>
							</div>

							<div class="form-group row">
								<label for="paterno" class="col-md-4 col-form-label text-md-right">Apellido paterno del enólogo/Wine Maker:</label>
								<div class="col-md-6">
									<input id="paterno" type="text" class="form-control {{ $errors->has('paterno') ? ' is-invalid' : ''  }}" name="paterno" value="{{ $edit ? $enologo->paterno : old('paterno') }}" required autofocus="">
									@if ($errors->has('paterno'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("paterno")}}</strong>
										</span>
									@endif
								</div>
							</div>

							<div class="form-group row">
								<label for="materno" class="col-md-4 col-form-label text-md-right">Apellido materno del enólogo/Wine Maker:</label>
								<div class="col-md-6">
									<input id="materno" type="text" class="form-control {{ $errors->has('materno') ? ' is-invalid' : ''  }}" name="materno" value="{{ $edit ? $enologo->materno : old('materno') }}" autofocus="">
									@if ($errors->has('materno'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("materno")}}</strong>
										</span>
									@endif
								</div>
							</div>

							<div class="form-group row">
								<label for="tipo" class="col-md-4 col-form-label text-md-right">Tipo:</label>
								<div class="col-md-6">
									<select id="tipo" class="form-control {{ $errors->has('tipo') ? ' is-invalid' : ''  }}" name="tipo" required autofocus="">
										<option value="">Seleccione el tipo</option>
										<option value="Enólogo" @if ($edit && $enologo->tipo == "Enólogo")
											{{-- expr --}}
											selected 
										@endif>Enólogo</option>
										<option value="Wine Maker" @if ($edit && $enologo->tipo == "Wine Maker")
											{{-- expr --}}
											selected 
										@endif>Wine Maker</option>
									</select>
									@if ($errors->has('tipo'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("tipo")}}</strong>
										</span>
									@endif
								</div>
							</div>

							<div class="form-group row">
								<label for="cv" class="col-md-4 col-form-label text-md-right">C.V.:</label>
								<div class="col-md-6">
									<textarea class="form-control {{$errors->has('cv') ? ' is-invalid' : ''  }}" id="cv" name="cv">{{ $edit ? $enologo->cv : old('cv') }}</textarea>
									@if ($errors->has('cv'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("cv")}}</strong>
										</span>
									@endif
								</div>
							</div>

						<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>
						</form>

						
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/enologo/index.blade.php
@extends('layouts.app2')
@section('content')
	{{-- expr --}}
	<div class="container-fluid">
		<div class="container">
			<div class="col">
				<h1>Enologos/Wine Makers</h1>
			</div>
			<div class="col-3 input-group input-group-lg mb-3">
		  		<a href="{{ route('enologos.create') }}" class="btn btn-primary">Agregar Nuevo Enologo/Wine Maker</a>
			</div>
		</div>
		<br>
		<br>
		<div class="container-fluid">
			<table class="table">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Nombre</th>
						<th scope="col">Apellidos</th>
						<th scope="col">tipo</th>
						<th scope="col">cv</th>
						<th scope="col">Acción</th>
					</tr>
				</thead>
				<tbody>
					@forelse ($enologos as $enologo)
						{{-- expr --}}
						<tr>
							<th col="row">{{$enologo->nombre}}</th>
							<th>{{$enologo->paterno}} {{$enologo->materno}}</th>
							<th>{{$enologo->tipo}}</th>
							<th>{{$enologo->cv}}</th>
							<th>
								<a class="btn btn-default" href="{{ route('enologos.edit',[$enologo]) }}">Editar</a>
								<form action="{{ route('enologos.destroy',[$enologo]) }}" method="POST">
									<input type="hidden" name="_method" value="DELETE">
									@csrf
									<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar este enologo?');">Eliminar</button>
								</form>
							</th>

						</tr>
					@empty
						{{-- empty expr --}}
						<div class="alert alert-danger" role="alert">
									<span>No hay enologos</span>
								</div>
					@endforelse
				</tbody>
			</table>
		</div>
	</div>
@endsection